### ISSUE TITLE
Where did the cipher password come from

### ISSUE THREAD

**Issue by luispablo** [pablouser1/SignTok#3]
Hi, sorry for opening an issue for this, but I found your tool super useful and would like to start using it. Sadly, I've been struggling with TikTok scraping and their constant changes and obstacles, so I'd like to know where this comes from, so I can trust that it can be found again whenever they choose to update it:

src/Signer.js: line 9

```javascript
  static PASSWORD = 'webapp1.0+202106'
```

Thanks a lot!!

**Comment by pablouser1** [comment]
I've got it from [tiktok-signature](https://github.com/carcabot/tiktok-signature), this project is just a port of that project but without having to use a headless browser. [This file](https://github.com/carcabot/tiktok-signature/blob/master/javascript/xttparams.js) contains a massive minified JS file, you can see this function at the end when prettified:

```javascript
function encryptParams(e) {
  const o = i.CryptoJS;
  const t = [];
  return (
    Object.keys(e).forEach((i) => {
      const o = i + "=" + e[i];
      t.push(o);
    }),
    t.push("is_encryption=1"),
    ((e, t) => {
      const i = ((e, t) => {
          let i = e.toString();
          const o = i.length;
          return (
            o < 16
              ? (i = new Array(16 - o + 1).join("0") + i)
              : o > 16 && (i = i.slice(0, 16)),
            i
          );
        })("webapp1.0+20210628"),
        n = o.enc.Utf8.parse(i);
      return o.AES.encrypt(e, n, {
        iv: n,
        mode: o.mode.CBC,
        padding: o.pad.Pkcs7,
      }).toString();
    })(t.join("&"))
  );
}
```

You would supose that 'webapp1.0+20210628' is the password, but if you read the code more extensively, that string is actually sliced to 'webapp1.0+202106', which is what is really used when encrypting (and decrypting) the query string.

I don't really know where this file came from though, _maybe_ someone got it from TikTok's servers at some point and started sharing it. It is used on all TikTok wrappers available publicly and I couldn't find it on their servers (most probably has been replaced with a harder to read/debug version).
