### ISSUE TITLE
Error: /lib64/libz.so.1:

### ISSUE THREAD

**Issue by lazezo2** [pablouser1/SignTok#6]
i try to deploy to vercel, but got this error

> [POST] /api/signatur
> 12:44:40:19
> 
> 2022-08-31T10:44:41.054Z	undefined	ERROR	Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /var/task/node_modules/canvas/build/Release/libpng16.so.16)    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12)    at Module.require (node:internal/modules/cjs/loader:1005:19)    at require (node:internal/modules/cjs/helpers:102:18)    at Object.<anonymous> (/var/task/node_modules/canvas/lib/bindings.js:3:18)    at Module._compile (node:internal/modules/cjs/loader:1105:14)    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)    at Module.load (node:internal/modules/cjs/loader:981:32)    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {  code: 'ERR_DLOPEN_FAILED'}RequestId: 57525d4b-dc05-483f-9b28-9f0533673e3d Error: Runtime exited with error: exit status 1Runtime.ExitError

tried to change package.json
by replace
`"start": "node api/index.js",`
with
` "start": "LD_PRELOAD='/opt/app-root/src/node_modules/sharp/vendor/lib/libz.so' node api/index.js","`
but same problem..
any help

**Comment by pablouser1** [comment]
Hi, in order to deploy SignTok to vercel you need to go to:

https://vercel.com/YOUR_USERNAME/YOUR_PROJECT_NAME/settings/environment-variables

And add a new enviromental variable named `LD_LIBRARY_PATH` and with the following value:

`/var/task/node_modules/canvas/build/Release:$LD_LIBRARY_PATH`

Rebuild and it should work properly

**Comment by lazezo2** [comment]
thanks, it's working like a charm
